"""
fractal.py
----------
Core numerical engine for computing a Julia set using the escape-time
algorithm, vectorized with numpy for speed.

A Julia set is generated by iterating z = z^2 + c for every point z in
the complex plane (c is a fixed constant that defines the shape of the
set). Points that never "escape" (never exceed magnitude 2) belong to
the filled Julia set; points that do escape are colored based on *how
fast* they escaped, which is what produces the fractal's fine detail
and self-similar structure at every zoom level.
"""

import numpy as np


def compute_julia(
    width: int,
    height: int,
    center: tuple[float, float] = (0.0, 0.0),
    scale: float = 1.5,
    c: complex = complex(-0.7, 0.27015),
    max_iter: int = 200,
):
    """
    Compute smoothed escape-time values for a Julia set.

    Parameters
    ----------
    width, height : output resolution in pixels
    center        : (re, im) center of the viewing window in the complex plane
    scale         : half-width of the viewing window (controls zoom level)
    c             : the Julia constant; different values give wildly
                    different fractal shapes
    max_iter      : maximum iterations before a point is considered "inside"
                    the set (higher = more detail near the boundary, slower)

    Returns
    -------
    smooth : (height, width) float64 array of smoothed iteration counts,
             used for continuous (banding-free) color gradients
    inside : (height, width) bool array, True where the point never escaped
    """
    x = np.linspace(center[0] - scale, center[0] + scale, width)
    y = np.linspace(center[1] - scale, center[1] + scale, height)
    X, Y = np.meshgrid(x, y)
    Z = X + 1j * Y

    smooth = np.zeros(Z.shape, dtype=np.float64)
    mask = np.ones(Z.shape, dtype=bool)  # True = still iterating (hasn't escaped)

    for i in range(max_iter):
        Z[mask] = Z[mask] ** 2 + c
        escaped = np.abs(Z) > 2
        newly_escaped = escaped & mask

        if np.any(newly_escaped):
            # Smooth (continuous) iteration count avoids visible color
            # banding — standard technique for escape-time fractals.
            with np.errstate(divide="ignore", invalid="ignore"):
                log_zn = np.log(np.abs(Z[newly_escaped]))
                nu = np.log(log_zn / np.log(2)) / np.log(2)
                smooth[newly_escaped] = np.nan_to_num(i + 1 - nu, nan=float(i))

        mask &= ~escaped
        if not mask.any():
            break

    inside = mask
    return smooth, inside


def compute_julia_supersampled(
    width: int,
    height: int,
    center: tuple[float, float] = (0.0, 0.0),
    scale: float = 1.5,
    c: complex = complex(-0.7, 0.27015),
    max_iter: int = 200,
    supersample: int = 2,
):
    """
    Same as compute_julia(), but renders at `supersample`x resolution and
    box-downsamples the result. The finest structure in a Julia set's
    spiral regions is genuinely sub-pixel at typical display resolutions
    (it's real detail, not noise) -- a single sample per pixel aliases
    into a speckled look. Supersampling averages that out. Only worth
    the extra compute for final exports, not for the interactive view.
    """
    hi_w, hi_h = width * supersample, height * supersample
    smooth_hi, inside_hi = compute_julia(hi_w, hi_h, center, scale, c, max_iter)

    def downsample(arr: np.ndarray) -> np.ndarray:
        return arr.reshape(height, supersample, width, supersample).mean(axis=(1, 3))

    smooth = downsample(smooth_hi)
    inside = downsample(inside_hi.astype(np.float64)) > 0.5
    return smooth, inside


# A small hand-picked set of Julia constants known to produce
# visually interesting, well-known fractal shapes.
CURATED_CONSTANTS = [
    complex(-0.70000, 0.27015),
    complex(-0.40000, 0.60000),
    complex(0.28500, 0.01000),
    complex(-0.83500, -0.23210),
    complex(-0.80000, 0.15600),
    complex(0.45000, 0.14280),
    complex(-0.75000, 0.11000),
    complex(-0.10000, 0.65100),
]